AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
   - 'bin/*'

Style/MutableConstant:
  Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - 'Gemfile'

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
   - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false
